version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ayurvedic-ecommerce
    overwrite: yes
permissions:
  - object: /home/ec2-user/ayurvedic-ecommerce
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user